export default [
  'a purple Netcentric t-shirt',
  'a purple Christmas tree decoration',
  'an unidentified piece of candy',
  'a #makeNetcentricAFunPlanceToWork sticker',
  'a \'Keep Calm and Do Your Tempo\' sticker',
  'a cheerful puppy',
  'office cat',
  'a wand of digging',
  'a Proof of Stremf',
  'a shotgun',
  'a pair of seven league boots',
  'Planepacked',
  'a Naughty Rudolph Cocktail',
  'a Berry Merry Christmas Cocktail',
  'a gin and tonic with cinnamon infused syrup',
  'a Japanese whisky on the rocks',
  'cinnamon-spiced apple juice',
  'Nespresso coffee',
  'a cup of the good coffee',
  'a tasty latte',
  'green toy snake',
  'a pair of Christmassy pyjamas',
  'a halfway done cigarette',
  'an iqos with no battery'
]
