export default [
  'a purple Netcentric t-shirt',
  'a purple Christmas tree decoration',
  'an unidentified piece of candy',
  'a #makeNetcentricAFunPlanceToWork sticker',
  'a \'Keep Calm and Do Your Tempo\' sticker',
  'a cheerful puppy',
  'office cat',
  'a wand of digging',
  'a Proof of Stremf',
  'a shotgun',
  'a pair of seven league boots',
  'Planepacked',
  'a hot mug of mulled wine',
  'a gin and tonic with cinnamon infused syrup',
  'a plain lager',
  'a michelada',
  'a bourbon hot toddy',
  'a Japanese whisky on the rocks',
  'homemade wine with Coca-cola',
  'cinnamon-spiced apple juice',
  'Nespresso coffee',
  'a cup of the good coffee',
  'a tasty latte',
  'green toy snake'
]